name: Deploy To GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: NPM Install 📦
        uses: bahmutov/npm-install@v1
        
      - name: Build Docs 🏗
        run: npm run docs:build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
          cname: docs.bagisto.com